Switch to inversify, add docs...
joelday/papyrus-lang pull request #168
Opened 2023-01-14 23:01 UTC by joelday

Totally going to change the merge strategy.

2023-01-14 23:08 UTC, joelday commented
I need to add the welcome message logic to open based on a comparison with the previously installed version.

2023-01-16 02:58 UTC, nikitalita requested changes

2023-01-16 02:58 UTC, nikitalita commented on src/papyrus-lang-vscode/src/server/LanguageClientHost.ts
> +                    return of(null);
of….?

2023-01-16 02:58 UTC, nikitalita commented on src/papyrus-lang-vscode/src/server/LanguageClientHost.ts
> +                    return of(null);
Oh, it’s reactive stuff.

2023-01-16 02:58 UTC, nikitalita commented on src/papyrus-lang-vscode/package.json
> +                        "label": "Papyrus: Skyrim Special Editio/Anniversary Editionn (with .ppj)",
```suggestion
                        "label": "Papyrus: Skyrim Special Edition/Anniversary Edition (with .ppj)",
```

2023-01-16 02:59 UTC, nikitalita approved these changes

2023-01-16 03:52 UTC, merged

2023-01-16 04:10 UTC, joelday commented
:tada: This PR is included in version 3.1.0-prerelease.2 :tada:

The release is available on:
- `v3.1.0-prerelease.2`
- [GitHub release](https://github.com/joelday/papyrus-lang/releases/tag/v3.1.0-prerelease.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: